import * as THREE from "three";
import type { GeneratedPoi, PoiDebugCandidate, PoiFootprint } from "./poi";
import { createPoiComponents } from "./poiStructures";
import type { StructureComponent } from "./structureTypes";
export { foundationDepth } from "./poiStructures";

export interface PoiDebugOptions { readonly level:"off"|"accepted"|"candidates" }

/** Presentation-only registry of low-poly POI renderers and shared components. */
export class PoiMeshFactory {
  private readonly box=this.shared(new THREE.BoxGeometry(1,1,1));
  private readonly roof=this.shared(createRoofGeometry());
  private readonly cylinder=this.shared(new THREE.CylinderGeometry(.5,.5,1,6));
  private readonly materials={wall:new THREE.MeshStandardMaterial({color:0xd8c49f,roughness:1}),lakeWall:new THREE.MeshStandardMaterial({color:0xa8b6a4,roughness:1}),roof:new THREE.MeshStandardMaterial({color:0x8d5f51,roughness:1,flatShading:true}),wood:new THREE.MeshStandardMaterial({color:0x80674d,roughness:1}),darkWood:new THREE.MeshStandardMaterial({color:0x57483d,roughness:1}),door:new THREE.MeshStandardMaterial({color:0x6e4b3d,roughness:1}),window:new THREE.MeshStandardMaterial({color:0x9fc7cf,roughness:.65}),chimney:new THREE.MeshStandardMaterial({color:0x786b62,roughness:1})};
  private readonly debugMaterial=new THREE.LineBasicMaterial({color:0xffcc44,depthTest:false,fog:false});
  private readonly acceptedDebugMaterial=new THREE.MeshBasicMaterial({color:0x32ff72,transparent:true,opacity:.78,depthTest:false,depthWrite:false,fog:false});
  private readonly rejectedDebugMaterial=new THREE.MeshBasicMaterial({color:0xff285f,transparent:true,opacity:.68,depthTest:false,depthWrite:false,fog:false});
  create(poi:GeneratedPoi):THREE.Group{const root=new THREE.Group();root.name=`poi:${poi.typeId}:${poi.id}`;root.userData={poiId:poi.id,poiType:poi.typeId};root.position.set(poi.position.x,poi.position.y,poi.position.z);root.rotation.y=poi.rotation;for(const component of createPoiComponents(poi))root.add(this.renderComponent(component,poi));freezeStaticTree(root);return root;}
  private renderComponent(component:StructureComponent,poi:GeneratedPoi):THREE.Mesh{const material=this.materials[component.material as keyof typeof this.materials],geometry=component.primitive==="roof"?this.roof:component.primitive==="cylinder"?this.cylinder:this.box;let length:number,height:number,width:number,rotation=component.rotation;if(component.primitive==="cylinder"){length=width=component.radius*2;height=component.height;}else if(component.primitive==="segment"){length=Math.hypot(component.end.x-component.start.x,component.end.z-component.start.z);height=component.height;width=component.thickness;rotation=-Math.atan2(component.end.z-component.start.z,component.end.x-component.start.x);}else{length=component.length;height=component.height;width=component.width;}const local=worldToLocal(poi,component.centre.x,component.centre.z),mesh=this.component(component.id.slice(poi.id.length+1),material,[length,height,width],[local.x,component.centre.y-poi.position.y,local.z],geometry);mesh.rotation.y=rotation-poi.rotation;const suffix=component.id.slice(poi.id.length+1);mesh.name=suffix==="roof"?"pitched-roof":suffix==="tower-mass"?"enclosed-tower-mass":suffix.startsWith("stilt:")?"short-stilt":suffix.startsWith("tower-leg:")?"tower-leg":suffix;return mesh;}
  private component(name:string,material:THREE.Material,scale:[number,number,number],position:[number,number,number],geometry:THREE.BufferGeometry=this.box):THREE.Mesh{const mesh=new THREE.Mesh(geometry,material);mesh.name=name;mesh.scale.set(...scale);mesh.position.set(...position);return mesh;}
  createDebug(pois:readonly GeneratedPoi[],candidates:readonly PoiDebugCandidate[],level:Exclude<PoiDebugOptions["level"],"off">):THREE.Group{const root=new THREE.Group();root.name="debug:pois";root.userData.level=level;const positions:number[]=[];const segment=(a:THREE.Vector3,b:THREE.Vector3)=>positions.push(a.x,a.y,a.z,b.x,b.y,b.z);for(const poi of pois){for(const zone of poi.zones){const points=outlinePoints(zone.footprint,poi.position.y+.08);for(let i=0;i<points.length;i++)segment(points[i]!,points[(i+1)%points.length]!);}segment(new THREE.Vector3(poi.position.x,poi.position.y+.12,poi.position.z),new THREE.Vector3(poi.entrance.position.x,poi.position.y+.12,poi.entrance.position.z));segment(new THREE.Vector3(poi.position.x,poi.position.y+.18,poi.position.z),new THREE.Vector3(poi.navigationAnchor.x,poi.navigationAnchor.y+.18,poi.navigationAnchor.z));if(poi.riverRelationship){const r=poi.riverRelationship,p=new THREE.Vector3(r.nearest.x,poi.position.y+.2,r.nearest.z);segment(new THREE.Vector3(poi.position.x,poi.position.y+.2,poi.position.z),p);segment(p,new THREE.Vector3(p.x+r.tangent.x*3,p.y,p.z+r.tangent.z*3));segment(p,new THREE.Vector3(p.x+r.normal.x*3,p.y,p.z+r.normal.z*3));}if(poi.dock)segment(new THREE.Vector3(poi.dock.shore.x,poi.dock.surfaceElevation+.2,poi.dock.shore.z),new THREE.Vector3(poi.dock.end.x,poi.dock.surfaceElevation+.2,poi.dock.end.z));}if(positions.length){const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(positions,3));const lines=new THREE.LineSegments(geometry,this.debugMaterial);lines.name="debug:poi-lines";root.add(lines);}const visibleCandidates=level==="candidates"?candidates:candidates.filter(candidate=>candidate.accepted);this.addCandidateBatch(root,visibleCandidates.filter(candidate=>candidate.accepted),true);this.addCandidateBatch(root,visibleCandidates.filter(candidate=>!candidate.accepted),false);freezeStaticTree(root);return root;}
  private addCandidateBatch(root:THREE.Group,candidates:readonly PoiDebugCandidate[],accepted:boolean):void{if(!candidates.length)return;const batch=new THREE.InstancedMesh(this.cylinder,accepted?this.acceptedDebugMaterial:this.rejectedDebugMaterial,candidates.length);batch.name=accepted?"debug:poi-candidates:accepted":"debug:poi-candidates:rejected";batch.userData.candidates=candidates;batch.renderOrder=100;const transform=new THREE.Object3D();candidates.forEach((candidate,index)=>{transform.position.set(candidate.x,.16,candidate.z);transform.scale.set(2.8,.22,2.8);transform.updateMatrix();batch.setMatrixAt(index,transform.matrix);});batch.instanceMatrix.needsUpdate=true;root.add(batch);}
  private shared<T extends THREE.BufferGeometry>(geometry:T):T{geometry.userData.poiShared=true;return geometry;}
  dispose():void{this.box.dispose();this.roof.dispose();this.cylinder.dispose();for(const material of Object.values(this.materials))material.dispose();this.debugMaterial.dispose();this.acceptedDebugMaterial.dispose();this.rejectedDebugMaterial.dispose();}
}
function outlinePoints(shape:PoiFootprint,y:number):THREE.Vector3[]{return shape.kind==="circle"?Array.from({length:24},(_,i)=>new THREE.Vector3(shape.x+Math.cos(i*Math.PI/12)*shape.radius,y,shape.z+Math.sin(i*Math.PI/12)*shape.radius)):Array.from({length:4},(_,i)=>{const u=i===0||i===3?-1:1,v=i<2?-1:1,c=Math.cos(shape.rotation),s=Math.sin(shape.rotation);return new THREE.Vector3(shape.x+c*shape.halfWidth*u-s*shape.halfDepth*v,y,shape.z+s*shape.halfWidth*u+c*shape.halfDepth*v);});}
function freezeStaticTree(root:THREE.Object3D):void{root.traverse(object=>{object.updateMatrix();object.matrixAutoUpdate=false;});}
function worldToLocal(poi:GeneratedPoi,x:number,z:number):{x:number;z:number}{const dx=x-poi.position.x,dz=z-poi.position.z,c=Math.cos(poi.rotation),s=Math.sin(poi.rotation);return{x:dx*c-dz*s,z:dx*s+dz*c};}
export function createRoofGeometry():THREE.BufferGeometry{const vertices=[-0.5,-0.5,-0.5,.5,-.5,-.5,0,.5,-.5,-.5,-.5,.5,.5,-.5,.5,0,.5,.5],indices=[0,2,1,3,4,5,1,5,4,1,2,5,0,3,5,0,5,2];const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(vertices,3));geometry.setIndex(indices);geometry.computeVertexNormals();return geometry;}
