import { describe,expect,it } from "vitest";
import type { GeneratedPoi } from "./poi";
import { createPoiStructure, POI_DIMENSIONS } from "./poiStructures";
import { queryStructureCollisions, resolveStructureMovement, selectStructureSupport, STRUCTURE_TANGENTIAL_RETENTION } from "./structureCollision";
import type { StructureCollisionDefinition } from "./structureTypes";
import { validateStructureDefinition } from "./structureTypes";

function poi(typeId:GeneratedPoi["typeId"],rotation=0,biome:GeneratedPoi["metadata"]["biome"]="plains",dock=false):GeneratedPoi{
 const raw={id:`poi:${typeId}`,typeId,position:{x:10,y:2,z:10},rotation,footprint:{kind:"rectangle",x:10,z:10,halfWidth:3,halfDepth:2.5,rotation} as const,zones:[],clearanceRadius:8,entrance:{position:{x:10,y:2,z:13},facing:rotation,direction:{x:0,z:1}},navigationAnchor:{x:10,y:2,z:13,kind:"entrance" as const},ownerChunk:{x:0,z:0},metadata:{biome,biomeWeights:{plains:1,forest:0,wetland:0,highlands:0,mountain:0,lake:0},candidateCell:{x:0,z:0,index:0},suitability:1,terrain:{averageHeight:2,minimumHeight:1.8,maximumHeight:2,heightVariation:.2,approximateSlope:.02,suggestedPlacementHeight:2},distanceToRiver:20,distanceToLake:20,vegetationDensity:0,plainsCoverage:1,localProminence:0},...(dock?{dock:{footprint:{kind:"rectangle",x:10,z:15,halfWidth:1.05,halfDepth:3,rotation},direction:{x:0,z:1},shore:{x:10,z:12},end:{x:10,y:.12,z:18},surfaceElevation:0}}:{})} as Omit<GeneratedPoi,"structure">;
 return{...raw,structure:createPoiStructure(raw as GeneratedPoi)};
}

describe("presentation-neutral POI structures",()=>{
 it("uses the visible house and foundation dimensions and rotation",()=>{const p=poi("plains-farmhouse",Math.PI/3),s=p.structure,w=s.boxes.find(b=>b.id.endsWith(":walls"))!,f=s.boxes.find(b=>b.kind==="foundation")!;expect([w.length,w.height,w.width]).toEqual(POI_DIMENSIONS.house.walls);expect(f.length).toBe(POI_DIMENSIONS.house.foundation[0]);expect(w.direction.x).toBeCloseTo(Math.cos(p.rotation));expect(JSON.stringify(s)).not.toContain("Object3D");});
 it("blocks a large wall impact and retains only the rejected tangent at 98%",()=>{const s=poi("plains-farmhouse").structure,r=resolveStructureMovement({x:6,y:2.76,z:9,yaw:0},{x:14,y:2.76,z:11,yaw:0},[s],.76);expect(r.transform.x).toBeLessThan(7);expect(r.slide).toBeDefined();expect(STRUCTURE_TANGENTIAL_RETENTION).toBe(.98);expect(r.transform.z).toBeGreaterThan(9.5);expect(Math.hypot(r.slide!.x,r.slide!.z)).toBeLessThanOrEqual(Math.hypot(8,2));});
 it("keeps cabin stilts and tower legs separate with open gaps",()=>{const cabin=poi("forest-cabin",0,"wetland").structure,tower=poi("highland-watchtower",0,"highlands").structure;expect(cabin.circles.filter(c=>c.kind==="stilt")).toHaveLength(4);expect(tower.circles.filter(c=>c.kind==="stilt")).toHaveLength(4);const through=resolveStructureMovement({x:10,y:2.76,z:6,yaw:0},{x:10,y:2.76,z:14,yaw:0},[tower],.76);expect(through.transform.z).toBeCloseTo(14);});
 it("models fence rails and posts without closing the entrance",()=>{const s=poi("plains-farmhouse").structure;expect(s.segments).toHaveLength(6);expect(s.circles.filter(c=>c.kind==="fence")).toHaveLength(12);const open=resolveStructureMovement({x:10,y:2.76,z:13,yaw:0},{x:10,y:2.76,z:15,yaw:0},[s],.76);expect(open.transform.z).toBeCloseTo(15);});
 it("supports a dock from above but never snaps a player up from beneath",()=>{const s=poi("lake-house",0,"plains",true).structure,dock=s.surfaces.find(v=>v.kind==="dock")!;expect(dock.width).toBe(2.1);expect(selectStructureSupport([s],10,15,dock.startHeight-.2,0,undefined)?.kind).toBe("dock");expect(selectStructureSupport([s],10,15,dock.startHeight-2,0,undefined)).toBeUndefined();const below=resolveStructureMovement({x:10,y:dock.startHeight-dock.thickness-1+.76,z:15,yaw:0},{x:10,y:dock.startHeight,z:15,yaw:0},[s],.76);expect(below.support).toBeUndefined();expect(below.ceilingHeight).toBeCloseTo(dock.startHeight-dock.thickness);});
 it("treats the visible dock thickness as a finite solid slab",()=>{const s=poi("lake-house",0,"plains",true).structure,dock=s.surfaces.find(v=>v.kind==="dock")!,side=resolveStructureMovement({x:7,y:-.4+.76,z:15,yaw:0},{x:13,y:-.4+.76,z:15,yaw:0},[s],.76);expect(side.transform.x).toBeLessThan(10-dock.width/2+.01);expect(dock.startHeight-dock.thickness).toBeCloseTo(.04);const below=resolveStructureMovement({x:7,y:-2+.76,z:15,yaw:0},{x:13,y:-2+.76,z:15,yaw:0},[s],.76),above=resolveStructureMovement({x:7,y:.3+.76,z:15,yaw:0},{x:13,y:.3+.76,z:15,yaw:0},[s],.76);expect(below.transform.x).toBeCloseTo(13);expect(above.transform.x).toBeCloseTo(13);});
 it("blocks porch sides while deriving support and ceiling from that same slab",()=>{const s=poi("lake-house").structure,porch=s.surfaces.find(v=>v.kind==="porch")!,blocked=resolveStructureMovement({x:10,y:2.1+.76,z:14.5,yaw:0},{x:10,y:2.1+.76,z:11.5,yaw:0},[s],.76);expect(blocked.transform.z).toBeGreaterThan(porch.centre.z+porch.width/2);const stepped=resolveStructureMovement({x:10,y:porch.startHeight-.2+.76,z:14,yaw:0},{x:10,y:porch.startHeight-.2+.76,z:12.85,yaw:0},[s],.76);expect(stepped.support?.id).toBe(porch.id);expect(stepped.transform.y-.76).toBeCloseTo(porch.startHeight);expect(porch.startHeight-porch.thickness).toBeCloseTo(2.44);});
 it("queries bridge, POI, and future generic definitions through one deduplicated path",()=>{const p=poi("forest-cabin"),generic:StructureCollisionDefinition={structureId:"future",ownerChunk:{x:0,z:0},source:"generic",boxes:[],circles:[],segments:[],surfaces:[],bounds:{minX:9,maxX:11,minZ:9,maxZ:11}},bridge={...generic,structureId:"bridge",source:"bridge" as const};const repository={get:(id:string)=>id==="0,0"?{pois:[p],bridges:[{collision:bridge},{collision:bridge}]}:undefined} as never;expect(queryStructureCollisions(repository,{x:9,z:9},{x:11,z:11}).map(s=>s.structureId)).toEqual(["bridge",p.id]);});
 it("validates solid-by-default component records at generation time",()=>{const s=poi("lake-house",0,"plains",true).structure;expect(()=>validateStructureDefinition(s)).not.toThrow();expect(()=>validateStructureDefinition({...s,surfaces:[{...s.surfaces[0]!,solid:false,walkable:true}]})).toThrow(/walkable slab/);expect(()=>validateStructureDefinition({...s,surfaces:[s.surfaces[0]!,s.surfaces[0]!]})).toThrow(/duplicate component id/);});

 it("derives every rendered POI component and collider from one classified inventory",()=>{for(const type of ["plains-farmhouse","lake-house","forest-cabin","highland-watchtower"] as const){const s=poi(type,0,type==="forest-cabin"?"wetland":"plains",type==="lake-house").structure;expect(s.components?.length).toBeGreaterThan(0);const colliderIds=new Set([...s.boxes,...s.circles,...s.segments,...s.surfaces].map(c=>c.id));for(const component of s.components!){expect(component.rendered).toBe(true);if(component.solid===false){expect(component.decorative).toBe(true);expect(colliderIds.has(component.id)).toBe(false);}else expect(colliderIds.has(component.id)).toBe(true);}}});
 it("makes the separately modelled bench seat and back solid, non-walkable, and sweep-collidable",()=>{const s=poi("lake-house").structure,components=s.components!.filter(c=>c.id.includes("bench-"));expect(components.map(c=>[c.id.split(":").at(-1),c.solid!==false,c.walkable,c.primitive])).toEqual([["bench-seat",true,false,"box"],["bench-back",true,false,"box"]]);const seat=resolveStructureMovement({x:4,y:2.8,z:11.2,yaw:0},{x:8,y:2.8,z:11.2,yaw:0},[s],.76);expect(seat.transform.x).toBeLessThan(5.73);const around=resolveStructureMovement({x:4,y:2.8,z:14.5,yaw:0},{x:8,y:2.8,z:14.5,yaw:0},[s],.76);expect(around.transform.x).toBeCloseTo(8);});
 it("slides at time of impact without the old endpoint-depenetration bounce",()=>{const s=poi("lake-house").structure,porch=s.surfaces.find(v=>v.kind==="porch")!,from={x:9,y:2.1+.76,z:14,yaw:0},to={x:11,y:2.1+.76,z:12,yaw:0},r=resolveStructureMovement(from,to,[s],.76);expect(Math.abs(r.transform.z-(porch.centre.z+porch.width/2+.38))).toBeLessThan(.01);expect(r.transform.x).toBeGreaterThan(9);});
});
